# Generated by Django 2.2.6 on 2019-11-30 17:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('UsersApp', '0025_auto_20191130_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='bookingid',
            field=models.UUIDField(default=uuid.UUID('fbd78251-b0c3-419e-82e9-bcc219417069'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='customer',
            field=models.CharField(max_length=100),
        ),
    ]
